name: Show "on pr" event details

on:
  pull_request:
    types:
      - opened
      - reopened

jobs:
  show-on-pr-details:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Show github stuff
        env:
          DEBUG: true
          HUB_VERBOSE: true
          GITHUB_TOKEN: ${{ secrets.JODH_GITHUB_ACTIONS_TOKEN }}
        run: |
          # FIXME: DEBUG:
          echo "::debug::GITHUB_WORKSPACE"
          echo "$GITHUB_WORKSPACE"

          # FIXME: DEBUG:
          echo "::debug::PWD"
          pwd
          ls -al

          # FIXME: DEBUG:
          echo "::debug::PATH: $PATH"
          echo $PATH

          export PATH="/usr/local/bin:$PATH"

          # FIXME: DEBUG:
          echo "::debug::hub"
          command -v hub || true

          # FIXME: DEBUG:
          echo "::debug::hub api user"
          GITHUB_TOKEN=${{ secrets.JODH_GITHUB_ACTIONS_TOKEN }} hub api user || true

          # FIXME: DEBUG:
          echo "::debug::hub issues"
          hub issue || true

          # FIXME: DEBUG:
          echo "::debug::hub PRs"
          hub pr list || true

          # FIXME: DEBUG:
          echo "::debug::git details"
          git ls-files -v || true
          git branch || true
          git remote -v || true
          git status || true

          # FIXME: DEBUG:
          echo "::debug::/usr/local/bin:"
          sudo ls -l /usr/local/bin || true

          # FIXME: DEBUG:
          echo "::debug::linked PRs"
          hub api -XGET search/issues -f 'q=repo:jamesodhunt-org/wibble is:issue is:open linked:pr' || true

          # FIXME: DEBUG:
          echo "::debug::linked issues"
          hub api -XGET search/issues -f 'q=repo:jamesodhunt-org/wibble is:pr is:open linked:issue' || true

          # FIXME: DEBUG:
          echo "::debug::issues"
          hub issue || true

          echo "FIXME: hello"
          kata-hub.sh list-issue-linked-prs || true
